feat(ru-KZ): autogenerated locale ru-KZ. Closes #108
sanity-io/locales pull request #110
Opened 2023-12-15 19:55 UTC by runeb

2023-12-19 10:45 UTC, yenbekbay requested changes
Everything looks good — just a few suggestions.

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/studio.ts
> +    'Показаны только активы принятых типов: <strong>{{acceptTypes}}</strong>',
```suggestion
    'Показаны только ресурсы принятых типов: <strong>{{acceptTypes}}</strong>',
```

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/studio.ts
> +  'search.action.select-asset': 'Выбрать актив',
```suggestion
  'search.action.select-asset': 'Выбрать ресурс',
```

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/studio.ts
> +    'В настоящее время поддерживается только источник активов по умолчанию.',
```suggestion
    'В настоящее время поддерживается только источник ресурсов по умолчанию.',
```

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/studio.ts
> +  'search.error.no-valid-asset-source-title': 'Не найдены действительные источники активов.',
```suggestion
  'search.error.no-valid-asset-source-title': 'Не найдены действительные источники ресурсов.',
```

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/validation.ts
> +  'object.asset-required': 'Требуется актив',
```suggestion
  'object.asset-required': 'Требуется ресурс',
```

2023-12-19 10:45 UTC, yenbekbay commented on locales/ru-KZ/src/vision.ts
> +  'result.end-to-end-time-label': 'Конец-к-концу',
```suggestion
  'result.end-to-end-time-label': 'Время от начала до конца',
```

2023-12-20 18:03 UTC, merged

2023-12-20 18:03 UTC, runeb commented
Thank you for your review, @yenbekbay!